### ISSUE TITLE
Readme link is broken

### ISSUE THREAD

**Issue by CMatias** [forter/security-101-for-saas-startups#42]
The link on the Readme page leads to a 404 page. It is trying to load /master/security.md instead of /english/security.md

**Comment by kirillyalta** [comment]
The link on the Readme page leads to a 404 page. It is trying to load /master/security.md instead of /english/security.md

**Comment by itaifrenkel** [comment]
Fixed with https://github.com/forter/security-101-for-saas-startups/pull/43
