### ISSUE TITLE
False information about Linux encryption

### ISSUE THREAD

**Issue by agilob** [forter/security-101-for-saas-startups#49]
>Linux users would require disk reformatting.

I understand that the tutorial is for basic users and it shouldn't cover things like dm-crypt, veracrypt etc, but the information cited above is not true and it's just spreading FUD across less technical users about Linux. There are a few ways to encrypt system or home folder for existing or future users. It's been widely supported for years now, eg. [This tutorial is from 2012](https://www.howtogeek.com/116032/how-to-encrypt-your-home-folder-after-installing-ubuntu/), [official guide for existing disk encryption from Canonical](https://help.ubuntu.com/community/PostInstallationEncryption) from 2012, there are more sources and tutorials how to do it, but let's just assume that those are enough for basic users.

**Comment by itaifrenkel** [comment]
@agilob Encrypting the home folder does not cover important system files. Would you be able to provide a link to encrypting the entire drive on ubuntu without re-installing the operating system?
If not, we can add a link to the tutorial you mentioned, but I suspect it's not on-par with mac/windows full disk encryption.

**Comment by dodekeract** [comment]
@itaifrenkel Worst case you can boot a live system from a stick and manually add a LUKS container on your hard drive. Not sure if it supports on-the-fly encryption, but with a copy onto a different drive it's definitely possible without re-installing.

**Comment by itaifrenkel** [comment]
@dodekeract I would need a blog post or a stackoveflow discussion that exaplains it. That's too low level for this repository.
